// 200 mensagens iniciais para o Gotas de Amor
// Categorias: bom-dia (20), boa-noite (20), amor (20), fe-espiritualidade (20),
//             familia (20), motivacao (20), amizade (20), aniversario (20),
//             reflexao (20), datas-comemorativas (20)

export interface MensagemSeed {
  titulo: string;
  texto: string;
  categoria: string;
  tags: string[];
  destaque: boolean;
  pexelsQuery: string;
}

export const mensagens: MensagemSeed[] = [
  // ── BOM DIA (20) ──────────────────────────────────────────────────────────
  {
    titulo: "O Dia Começa Com Você",
    texto: "Bom dia! Que este dia seja tão especial quanto você é para mim. Levanta com fé, sorri para a vida e vai — o mundo precisa da sua luz.",
    categoria: "bom-dia", tags: ["bom dia", "manhã", "motivação", "amor"], destaque: true,
    pexelsQuery: "sunrise morning light warm",
  },
  {
    titulo: "Manhã de Gratidão",
    texto: "Mais um dia de vida é mais um presente. Abra os olhos, respire fundo e agradeça. Bom dia!",
    categoria: "bom-dia", tags: ["bom dia", "gratidão", "manhã"], destaque: false,
    pexelsQuery: "morning gratitude peaceful sunrise",
  },
  {
    titulo: "Recomeço Todo Dia",
    texto: "Cada manhã é uma página em branco. Você decide o que vai escrever nela. Bom dia, escreva algo bonito hoje.",
    categoria: "bom-dia", tags: ["bom dia", "recomeço", "motivação"], destaque: false,
    pexelsQuery: "new day fresh start morning",
  },
  {
    titulo: "Sol de Dentro",
    texto: "O sol nasceu lá fora, mas o maior brilho vem de dentro de você. Bom dia! Que sua luz ilumine tudo ao redor.",
    categoria: "bom-dia", tags: ["bom dia", "luz", "inspiração"], destaque: false,
    pexelsQuery: "sunlight window morning golden",
  },
  {
    titulo: "Força pra Hoje",
    texto: "Bom dia! Que você tenha energia para os desafios, paciência para os momentos difíceis e alegria pra celebrar cada vitória.",
    categoria: "bom-dia", tags: ["bom dia", "força", "energia"], destaque: false,
    pexelsQuery: "morning energy strength coffee",
  },
  {
    titulo: "Manhã Abençoada",
    texto: "Que Deus abençoe seu dia, seu caminho e cada pessoa que você encontrar. Bom dia com muito amor!",
    categoria: "bom-dia", tags: ["bom dia", "bênção", "fé"], destaque: true,
    pexelsQuery: "blessed morning prayer sunrise",
  },
  {
    titulo: "Hoje Vai Ser Bom",
    texto: "Bom dia! Decida agora: hoje vai ser um dia incrível. Às vezes é só uma decisão que muda tudo.",
    categoria: "bom-dia", tags: ["bom dia", "positividade", "decisão"], destaque: false,
    pexelsQuery: "positive morning smile happy",
  },
  {
    titulo: "Presente da Manhã",
    texto: "Acordar é um presente. Respirar é um presente. Você é um presente. Bom dia!",
    categoria: "bom-dia", tags: ["bom dia", "presente", "vida"], destaque: false,
    pexelsQuery: "morning gift life beautiful",
  },
  {
    titulo: "Café e Esperança",
    texto: "Bom dia! Que seu café esteja quente, seu coração leve e seus sonhos mais perto do que ontem.",
    categoria: "bom-dia", tags: ["bom dia", "café", "sonhos"], destaque: false,
    pexelsQuery: "coffee morning cup warm cozy",
  },
  {
    titulo: "Amanhecer Bonito",
    texto: "O amanhecer não pergunta se você está pronto. Ele simplesmente vem. Então vai — bom dia!",
    categoria: "bom-dia", tags: ["bom dia", "amanhecer", "coragem"], destaque: false,
    pexelsQuery: "beautiful dawn sunrise sky",
  },
  {
    titulo: "Manhã de Paz",
    texto: "Que a paz de Deus guarde seu coração e sua mente neste novo dia. Bom dia!",
    categoria: "bom-dia", tags: ["bom dia", "paz", "fé"], destaque: false,
    pexelsQuery: "peaceful morning calm serene",
  },
  {
    titulo: "Primeiro Passo",
    texto: "Bom dia! O primeiro passo do dia é o mais importante. Dê-o com confiança.",
    categoria: "bom-dia", tags: ["bom dia", "confiança", "começo"], destaque: false,
    pexelsQuery: "first step morning walk path",
  },
  {
    titulo: "Sorriso na Manhã",
    texto: "Um sorriso logo cedo muda o tom do dia inteiro. Sorria! Bom dia.",
    categoria: "bom-dia", tags: ["bom dia", "sorriso", "alegria"], destaque: false,
    pexelsQuery: "smile morning happy woman",
  },
  {
    titulo: "Nova Chance",
    texto: "Bom dia! Ontem ficou no passado. Hoje é uma nova chance de ser quem você quer ser.",
    categoria: "bom-dia", tags: ["bom dia", "chance", "recomeço"], destaque: false,
    pexelsQuery: "new chance morning fresh",
  },
  {
    titulo: "Cuide de Você",
    texto: "Bom dia! Não esqueça de beber água, respirar fundo e se tratar com gentileza hoje.",
    categoria: "bom-dia", tags: ["bom dia", "autocuidado", "saúde"], destaque: false,
    pexelsQuery: "self care morning routine wellness",
  },
  {
    titulo: "Manhã Radiante",
    texto: "Que sua manhã seja radiante como o sol que nasce, e seu dia tão pleno quanto seu coração merece. Bom dia!",
    categoria: "bom-dia", tags: ["bom dia", "radiante", "pleno"], destaque: false,
    pexelsQuery: "radiant morning sunbeams sky",
  },
  {
    titulo: "Desperta e Brilha",
    texto: "Bom dia! Levanta, se arruma, sai por aí e brilha. O mundo precisa do que só você tem.",
    categoria: "bom-dia", tags: ["bom dia", "brilho", "motivação"], destaque: true,
    pexelsQuery: "morning glow shine sunrise woman",
  },
  {
    titulo: "Manhã Com Amor",
    texto: "Mandando um bom dia cheio de amor pra você. Que seu coração esteja leve e seus passos firmes.",
    categoria: "bom-dia", tags: ["bom dia", "amor", "carinho"], destaque: false,
    pexelsQuery: "morning love warmth heart",
  },
  {
    titulo: "O Melhor Está Por Vir",
    texto: "Bom dia! Não importa o que ontem foi. O melhor ainda está por vir — e começa agora.",
    categoria: "bom-dia", tags: ["bom dia", "esperança", "futuro"], destaque: false,
    pexelsQuery: "hope horizon morning light",
  },
  {
    titulo: "Amanhã Começa Hoje",
    texto: "Bom dia! O que você fizer hoje vai moldar o seu amanhã. Que seja algo que te orgulhe.",
    categoria: "bom-dia", tags: ["bom dia", "propósito", "futuro"], destaque: false,
    pexelsQuery: "purpose morning planning goals",
  },

  // ── BOA NOITE (20) ────────────────────────────────────────────────────────
  {
    titulo: "Noite de Descanso",
    texto: "Boa noite! Que você descanse tudo que cansou, solte tudo que pesou e acorde amanhã renovado.",
    categoria: "boa-noite", tags: ["boa noite", "descanso", "paz"], destaque: true,
    pexelsQuery: "night rest peaceful sleep bedroom",
  },
  {
    titulo: "Sonhos Lindos",
    texto: "Fecha os olhos e vai. Que seus sonhos sejam tão lindos quanto você merece. Boa noite!",
    categoria: "boa-noite", tags: ["boa noite", "sonhos", "carinho"], destaque: false,
    pexelsQuery: "sweet dreams night stars",
  },
  {
    titulo: "Gratidão Noturna",
    texto: "Antes de dormir, pensa em algo bom que aconteceu hoje. Sempre tem. Boa noite!",
    categoria: "boa-noite", tags: ["boa noite", "gratidão", "reflexão"], destaque: false,
    pexelsQuery: "night gratitude moon quiet",
  },
  {
    titulo: "Paz na Madrugada",
    texto: "Que a paz de Deus cubra você como um manto nessa noite. Boa noite com muito amor.",
    categoria: "boa-noite", tags: ["boa noite", "paz", "fé"], destaque: false,
    pexelsQuery: "moonlight peaceful night sky",
  },
  {
    titulo: "Fim de Dia Bem Vivido",
    texto: "Você chegou até aqui. Isso já é motivo de orgulho. Descanse, guerreiro. Boa noite!",
    categoria: "boa-noite", tags: ["boa noite", "orgulho", "descanso"], destaque: true,
    pexelsQuery: "sunset end of day rest",
  },
  {
    titulo: "Silêncio da Noite",
    texto: "No silêncio da noite, que seu coração encontre a calma que o dia não deu. Boa noite!",
    categoria: "boa-noite", tags: ["boa noite", "silêncio", "calma"], destaque: false,
    pexelsQuery: "night silence calm dark peaceful",
  },
  {
    titulo: "Anjos Guardiões",
    texto: "Boa noite! Que os anjos guardem seu sono e Deus cuide de tudo o que você não consegue controlar.",
    categoria: "boa-noite", tags: ["boa noite", "proteção", "fé"], destaque: false,
    pexelsQuery: "night protection stars guardian",
  },
  {
    titulo: "Deixa Ir",
    texto: "Boa noite! Deixa ir tudo que te machucou hoje. Amanhã é outro dia, outra chance, outro começo.",
    categoria: "boa-noite", tags: ["boa noite", "soltar", "recomeço"], destaque: false,
    pexelsQuery: "let go night stars freedom",
  },
  {
    titulo: "Noite Estrelada",
    texto: "Que cada estrela no céu te lembre que você não está sozinho. Boa noite!",
    categoria: "boa-noite", tags: ["boa noite", "estrelas", "companhia"], destaque: false,
    pexelsQuery: "starry night sky stars universe",
  },
  {
    titulo: "Recarregando",
    texto: "Dormir é recarregar a alma. Amanhã você acorda mais forte. Boa noite!",
    categoria: "boa-noite", tags: ["boa noite", "força", "energia"], destaque: false,
    pexelsQuery: "night recharge rest sleep",
  },
  {
    titulo: "Pense No Bem",
    texto: "Boa noite! Antes de fechar os olhos, pense em alguém que você ama. É o melhor travesseiro.",
    categoria: "boa-noite", tags: ["boa noite", "amor", "carinho"], destaque: false,
    pexelsQuery: "night love warmth cozy",
  },
  {
    titulo: "Missão Cumprida",
    texto: "Mais um dia de missão cumprida. Você pode dormir em paz. Boa noite!",
    categoria: "boa-noite", tags: ["boa noite", "conquista", "paz"], destaque: false,
    pexelsQuery: "night achievement rest peace",
  },
  {
    titulo: "Noite Abençoada",
    texto: "Que Deus abençoe seu sono, seus sonhos e o amanhecer que vai chegar. Boa noite!",
    categoria: "boa-noite", tags: ["boa noite", "bênção", "fé"], destaque: false,
    pexelsQuery: "blessed night moon prayer",
  },
  {
    titulo: "Fim do Cansaço",
    texto: "O cansaço do corpo pede cama. O cansaço da alma pede silêncio. Que você encontre os dois. Boa noite!",
    categoria: "boa-noite", tags: ["boa noite", "descanso", "alma"], destaque: false,
    pexelsQuery: "tired night rest cozy bed",
  },
  {
    titulo: "Abraço Noturno",
    texto: "Mandando um abraço virtual pra você atravessar a noite mais quentinho. Boa noite!",
    categoria: "boa-noite", tags: ["boa noite", "abraço", "carinho"], destaque: true,
    pexelsQuery: "night hug cozy warmth",
  },
  {
    titulo: "Amanhã Com Fé",
    texto: "Boa noite! Durma com fé de que amanhã vai ser melhor. Porque vai.",
    categoria: "boa-noite", tags: ["boa noite", "fé", "esperança"], destaque: false,
    pexelsQuery: "faith night hope morning",
  },
  {
    titulo: "Reflexo da Lua",
    texto: "A lua está aí pra te fazer companhia. Boa noite, você nunca está sozinho.",
    categoria: "boa-noite", tags: ["boa noite", "lua", "companhia"], destaque: false,
    pexelsQuery: "moon reflection night water",
  },
  {
    titulo: "Noite de Cura",
    texto: "Que essa noite cure o que o dia machucou. Durma bem. Boa noite!",
    categoria: "boa-noite", tags: ["boa noite", "cura", "descanso"], destaque: false,
    pexelsQuery: "healing night rest peaceful",
  },
  {
    titulo: "Valeu Hoje",
    texto: "Valeu por cada esforço de hoje. Vai descansar, você merece. Boa noite!",
    categoria: "boa-noite", tags: ["boa noite", "esforço", "merecimento"], destaque: false,
    pexelsQuery: "night deserve rest grateful",
  },
  {
    titulo: "Noite Tranquila",
    texto: "Que sua noite seja tão tranquila quanto o rio que corre devagar. Boa noite!",
    categoria: "boa-noite", tags: ["boa noite", "tranquilidade", "paz"], destaque: false,
    pexelsQuery: "calm river night tranquil",
  },

  // ── AMOR (20) ─────────────────────────────────────────────────────────────
  {
    titulo: "Você É Meu Lugar",
    texto: "Em qualquer lugar do mundo, o meu lugar favorito é ao seu lado. Te amo mais do que as palavras conseguem dizer.",
    categoria: "amor", tags: ["amor", "casal", "romance"], destaque: true,
    pexelsQuery: "couple love together romance",
  },
  {
    titulo: "Escolho Você Todo Dia",
    texto: "Amor não é só sentimento. É uma escolha que faço todo dia ao acordar. E todo dia eu escolho você.",
    categoria: "amor", tags: ["amor", "escolha", "compromisso"], destaque: true,
    pexelsQuery: "couple choice love daily",
  },
  {
    titulo: "Meu Lar É Você",
    texto: "Não preciso de um endereço pra me sentir em casa. Basta estar com você.",
    categoria: "amor", tags: ["amor", "lar", "presença"], destaque: false,
    pexelsQuery: "home love couple cozy",
  },
  {
    titulo: "Saudade de Você",
    texto: "Saudade é amar de longe. E mesmo de longe, você é tudo pra mim.",
    categoria: "amor", tags: ["amor", "saudade", "distância"], destaque: false,
    pexelsQuery: "missing someone love longing",
  },
  {
    titulo: "Primeiro e Último",
    texto: "Quero que você seja o primeiro pensamento do meu dia e o último da minha noite. Para sempre.",
    categoria: "amor", tags: ["amor", "pensamento", "sempre"], destaque: false,
    pexelsQuery: "love morning night couple forever",
  },
  {
    titulo: "Amor Simples",
    texto: "Não precisa ser perfeito. Só precisa ser real, ser seu, ser nosso. Te amo do jeito que você é.",
    categoria: "amor", tags: ["amor", "real", "imperfeito"], destaque: false,
    pexelsQuery: "simple love real couple tender",
  },
  {
    titulo: "Com Você Faz Sentido",
    texto: "Muita coisa na vida não faz sentido. Mas o que sinto por você faz todo sentido do mundo.",
    categoria: "amor", tags: ["amor", "sentido", "sentimento"], destaque: false,
    pexelsQuery: "love makes sense couple together",
  },
  {
    titulo: "Olhar Que Diz Tudo",
    texto: "Tem um olhar seu que dispensa palavras. Eu sei tudo o que você sente só de te olhar.",
    categoria: "amor", tags: ["amor", "olhar", "conexão"], destaque: true,
    pexelsQuery: "couple eye contact love gaze",
  },
  {
    titulo: "Minha Paz",
    texto: "Num mundo cheio de barulho, você é a minha paz. Obrigado por existir na minha vida.",
    categoria: "amor", tags: ["amor", "paz", "gratidão"], destaque: false,
    pexelsQuery: "peace love calm couple",
  },
  {
    titulo: "Amor Que Cuida",
    texto: "Amar é cuidar quando a pessoa não pede. É estar sem precisar ser chamado. Isso é o que sinto por você.",
    categoria: "amor", tags: ["amor", "cuidado", "presença"], destaque: false,
    pexelsQuery: "care love couple tender",
  },
  {
    titulo: "Rindo Com Você",
    texto: "Encontrar alguém com quem você ri de verdade é raro. Você é esse alguém pra mim.",
    categoria: "amor", tags: ["amor", "riso", "alegria"], destaque: false,
    pexelsQuery: "laughing couple happy joy",
  },
  {
    titulo: "Te Amar É Fácil",
    texto: "Disseram que amar é difícil. Mas te amar é a coisa mais natural que já senti.",
    categoria: "amor", tags: ["amor", "natural", "sentimento"], destaque: false,
    pexelsQuery: "easy love natural couple sweet",
  },
  {
    titulo: "Minha Pessoa",
    texto: "Você não é só namorado/a. Você é minha pessoa — aquela que eu quero contar tudo, dividir tudo, ser tudo.",
    categoria: "amor", tags: ["amor", "parceiro", "cumplicidade"], destaque: false,
    pexelsQuery: "my person soulmate couple close",
  },
  {
    titulo: "Amor Que Cresce",
    texto: "Pensei que não era possível te amar mais. Aí passou o tempo e provei que eu estava errado.",
    categoria: "amor", tags: ["amor", "crescimento", "tempo"], destaque: true,
    pexelsQuery: "growing love couple over time",
  },
  {
    titulo: "Detalhes Que Amo",
    texto: "Amo em você os detalhes que o mundo ignora. Esses pequenos jeitos seus que só eu conheço.",
    categoria: "amor", tags: ["amor", "detalhes", "único"], destaque: false,
    pexelsQuery: "love details couple intimate",
  },
  {
    titulo: "Seu Abraço",
    texto: "Nenhum lugar no mundo é mais confortável do que o seu abraço. Fico lá e o tempo para.",
    categoria: "amor", tags: ["amor", "abraço", "conforto"], destaque: false,
    pexelsQuery: "couple hug embrace warm",
  },
  {
    titulo: "Por Você",
    texto: "Por você eu faria muita coisa que nunca imaginei fazer. Isso me diz o quanto te amo.",
    categoria: "amor", tags: ["amor", "sacrifício", "dedicação"], destaque: false,
    pexelsQuery: "love sacrifice dedication couple",
  },
  {
    titulo: "Amor de Verdade",
    texto: "Amor de verdade não some quando bate a saudade. Ele aparece quando bate o medo. E o meu aparece sempre.",
    categoria: "amor", tags: ["amor", "verdade", "presença"], destaque: false,
    pexelsQuery: "true love real couple support",
  },
  {
    titulo: "Nossa História",
    texto: "Nossa história não é perfeita, mas é nossa. E eu não trocaria por nenhuma outra do mundo.",
    categoria: "amor", tags: ["amor", "história", "casal"], destaque: false,
    pexelsQuery: "our story couple journey together",
  },
  {
    titulo: "Sempre Você",
    texto: "Se eu pudesse escolher de novo, escolheria você. Mil vezes, sempre você.",
    categoria: "amor", tags: ["amor", "escolha", "sempre"], destaque: true,
    pexelsQuery: "always you love couple forever",
  },

  // ── FÉ E ESPIRITUALIDADE (20) ─────────────────────────────────────────────
  {
    titulo: "Na Mão de Deus",
    texto: "Quando você não sabe mais o que fazer, entrega nas mãos de Deus. Ele sabe o que você não consegue ver.",
    categoria: "fe-espiritualidade", tags: ["fé", "Deus", "confiança"], destaque: true,
    pexelsQuery: "faith hands prayer light",
  },
  {
    titulo: "Força Que Vem do Alto",
    texto: "Quando a sua força acabar, lembre que tem uma força maior disponível pra você. É só pedir.",
    categoria: "fe-espiritualidade", tags: ["fé", "força", "oração"], destaque: false,
    pexelsQuery: "spiritual strength light above",
  },
  {
    titulo: "Deus Não Esquece",
    texto: "Deus não esqueceu de você. Às vezes o silêncio é parte do plano. Confie.",
    categoria: "fe-espiritualidade", tags: ["fé", "confiança", "espera"], destaque: false,
    pexelsQuery: "trust God faith waiting",
  },
  {
    titulo: "Milagre a Caminho",
    texto: "Não desista antes do milagre. Ele pode estar na próxima esquina.",
    categoria: "fe-espiritualidade", tags: ["fé", "milagre", "esperança"], destaque: true,
    pexelsQuery: "miracle faith hope light coming",
  },
  {
    titulo: "Oração Que Muda",
    texto: "Uma oração sincera muda o coração. E quando o coração muda, tudo ao redor muda também.",
    categoria: "fe-espiritualidade", tags: ["fé", "oração", "mudança"], destaque: false,
    pexelsQuery: "prayer sincere heart faith",
  },
  {
    titulo: "Propósito Maior",
    texto: "Você está aqui por uma razão que vai além do que você consegue entender. Isso se chama propósito.",
    categoria: "fe-espiritualidade", tags: ["fé", "propósito", "razão"], destaque: false,
    pexelsQuery: "purpose greater meaning spiritual",
  },
  {
    titulo: "Deus no Detalhe",
    texto: "Deus está nos grandes milagres e nos pequenos detalhes. Presta atenção no que acontece ao seu redor.",
    categoria: "fe-espiritualidade", tags: ["fé", "detalhe", "presença"], destaque: false,
    pexelsQuery: "God detail small miracle nature",
  },
  {
    titulo: "Paz Que Excede",
    texto: "Existe uma paz que vai além de toda compreensão humana. É essa que Deus quer te dar.",
    categoria: "fe-espiritualidade", tags: ["fé", "paz", "Deus"], destaque: false,
    pexelsQuery: "divine peace beyond understanding",
  },
  {
    titulo: "Testemunho Vivo",
    texto: "Sua vida é um testemunho. Cada vez que você se levantou depois de cair, você provou que Deus é fiel.",
    categoria: "fe-espiritualidade", tags: ["fé", "testemunho", "fidelidade"], destaque: true,
    pexelsQuery: "testimony rising faith faithful",
  },
  {
    titulo: "Guardado por Deus",
    texto: "Você pode não perceber, mas Deus já livrou você de coisas que você nem imagina. Ele cuida.",
    categoria: "fe-espiritualidade", tags: ["fé", "proteção", "cuidado"], destaque: false,
    pexelsQuery: "protected by God care faith",
  },
  {
    titulo: "Fé Que Move",
    texto: "A fé não move montanhas porque você grita alto. Move porque você acredita em silêncio.",
    categoria: "fe-espiritualidade", tags: ["fé", "crença", "silêncio"], destaque: false,
    pexelsQuery: "faith silence believe mountain",
  },
  {
    titulo: "Plano Perfeito",
    texto: "O plano de Deus pra sua vida é melhor do que qualquer coisa que você conseguiu planejar.",
    categoria: "fe-espiritualidade", tags: ["fé", "plano", "confiança"], destaque: false,
    pexelsQuery: "God plan perfect trust future",
  },
  {
    titulo: "Não Estou Sozinho",
    texto: "Mesmo nas noites mais escuras, Deus está lá. Você nunca está sozinho de verdade.",
    categoria: "fe-espiritualidade", tags: ["fé", "solidão", "presença"], destaque: false,
    pexelsQuery: "not alone dark night faith light",
  },
  {
    titulo: "Perseverar na Fé",
    texto: "Continue. A fé não é sentir que vai dar certo. É continuar mesmo quando parece que não vai.",
    categoria: "fe-espiritualidade", tags: ["fé", "perseverança", "força"], destaque: true,
    pexelsQuery: "persevere faith continue strong",
  },
  {
    titulo: "Gratidão Como Oração",
    texto: "Às vezes a melhor oração é simplesmente dizer obrigado. Por tudo, até pelo que dói.",
    categoria: "fe-espiritualidade", tags: ["fé", "gratidão", "oração"], destaque: false,
    pexelsQuery: "gratitude prayer thankful faith",
  },
  {
    titulo: "Tempo de Deus",
    texto: "O tempo de Deus não atrasa nem adianta. Chega no momento certo. Confie na espera.",
    categoria: "fe-espiritualidade", tags: ["fé", "tempo", "espera"], destaque: false,
    pexelsQuery: "God timing wait trust patience",
  },
  {
    titulo: "Amor Incondicional",
    texto: "Deus te ama não pelo que você faz, mas pelo que você é. Esse amor não tem condição.",
    categoria: "fe-espiritualidade", tags: ["fé", "amor", "incondicional"], destaque: false,
    pexelsQuery: "unconditional love God light",
  },
  {
    titulo: "Renova as Forças",
    texto: "Aqueles que esperam no Senhor renovam as suas forças. Aguenta. A renovação está vindo.",
    categoria: "fe-espiritualidade", tags: ["fé", "renovação", "força"], destaque: false,
    pexelsQuery: "renew strength faith eagle soar",
  },
  {
    titulo: "Deus Vê o Seu Esforço",
    texto: "Pode ser que ninguém veja o quanto você tenta. Mas Deus vê. E isso tem valor.",
    categoria: "fe-espiritualidade", tags: ["fé", "esforço", "reconhecimento"], destaque: false,
    pexelsQuery: "God sees effort value faith",
  },
  {
    titulo: "Luz No Final",
    texto: "A luz no final do túnel não é ilusão. É a fé que não deixou você parar no meio.",
    categoria: "fe-espiritualidade", tags: ["fé", "luz", "esperança"], destaque: true,
    pexelsQuery: "light end tunnel hope faith",
  },

  // ── FAMÍLIA (20) ──────────────────────────────────────────────────────────
  {
    titulo: "Família É Tudo",
    texto: "No fim do dia, o que fica de verdade é família. Cuide de quem é seu.",
    categoria: "familia", tags: ["família", "amor", "cuidado"], destaque: true,
    pexelsQuery: "family together love home",
  },
  {
    titulo: "Raízes e Asas",
    texto: "Família boa te dá raízes pra se firmar e asas pra voar. Obrigado por ser minha base.",
    categoria: "familia", tags: ["família", "raízes", "suporte"], destaque: false,
    pexelsQuery: "family roots wings love",
  },
  {
    titulo: "Mesa da Família",
    texto: "A mesa da família é onde os maiores assuntos são resolvidos sem protocolo. Com comida, barulho e amor.",
    categoria: "familia", tags: ["família", "reunião", "amor"], destaque: false,
    pexelsQuery: "family dinner table together",
  },
  {
    titulo: "Pai, Meu Herói",
    texto: "Pai não precisa usar capa pra ser herói. O meu usa avental, camisa de trabalho e nunca desiste.",
    categoria: "familia", tags: ["família", "pai", "herói"], destaque: true,
    pexelsQuery: "father son daughter hero love",
  },
  {
    titulo: "Mãe, Minha Fortaleza",
    texto: "Minha mãe é o tipo de força que não se explica. Só se sente. E eu sinto todo dia.",
    categoria: "familia", tags: ["família", "mãe", "força"], destaque: true,
    pexelsQuery: "mother strength love family",
  },
  {
    titulo: "Irmãos de Alma",
    texto: "Irmão não é só quem nasce junto. É quem cresce junto, briga junto e se ama do mesmo jeito.",
    categoria: "familia", tags: ["família", "irmão", "cumplicidade"], destaque: false,
    pexelsQuery: "siblings brothers sisters love together",
  },
  {
    titulo: "Avó, Meu Lar",
    texto: "A casa da vovó é o tipo de lugar que cheira a aconchego. Lá, tudo é mais seguro.",
    categoria: "familia", tags: ["família", "avó", "saudade"], destaque: false,
    pexelsQuery: "grandmother grandchild love warm",
  },
  {
    titulo: "Filhos São Dádiva",
    texto: "Filhos chegam e mudam tudo. A rotina, o sono, as prioridades. E o coração, que nunca mais cabe no peito.",
    categoria: "familia", tags: ["família", "filhos", "amor"], destaque: false,
    pexelsQuery: "children parent love family joy",
  },
  {
    titulo: "Família Imperfeita",
    texto: "Família perfeita não existe. Mas família que se ama apesar de tudo? Essa sim é real e vale tudo.",
    categoria: "familia", tags: ["família", "imperfeição", "amor real"], destaque: false,
    pexelsQuery: "imperfect family real love together",
  },
  {
    titulo: "Herança Maior",
    texto: "A maior herança que você pode deixar pros filhos não é dinheiro. É exemplo, caráter e amor.",
    categoria: "familia", tags: ["família", "herança", "exemplo"], destaque: true,
    pexelsQuery: "family legacy values example",
  },
  {
    titulo: "Saudade de Casa",
    texto: "Saudade de casa não é saudade do lugar. É saudade das pessoas que fazem aquele lugar ser lar.",
    categoria: "familia", tags: ["família", "saudade", "lar"], destaque: false,
    pexelsQuery: "home family nostalgia warmth",
  },
  {
    titulo: "Amor de Pai",
    texto: "O amor de pai não faz barulho. Ele aparece na conta paga, na presença que nunca falta, no silêncio que protege.",
    categoria: "familia", tags: ["família", "pai", "amor silencioso"], destaque: false,
    pexelsQuery: "father love silent protect family",
  },
  {
    titulo: "Mãe Que Ora",
    texto: "Mãe que ora pelo filho é escudo que ninguém vê mas todo mundo sente. Obrigado pelas suas orações.",
    categoria: "familia", tags: ["família", "mãe", "oração"], destaque: false,
    pexelsQuery: "mother pray children faith protection",
  },
  {
    titulo: "Crescer Junto",
    texto: "Crescer junto é o presente mais bonito que a família dá. Cada fase, cada luta, cada risada compartilhada.",
    categoria: "familia", tags: ["família", "crescimento", "memória"], destaque: false,
    pexelsQuery: "family grow together over years",
  },
  {
    titulo: "Neto Ilumina",
    texto: "Neto é a segunda chance de Deus de ver os avós sorrirem como crianças.",
    categoria: "familia", tags: ["família", "neto", "avós"], destaque: false,
    pexelsQuery: "grandparents grandchildren joy love",
  },
  {
    titulo: "Casa Cheia",
    texto: "Casa cheia de família pode ser barulhento, confuso e cansativo. Mas é o tipo de bagunça que faz falta.",
    categoria: "familia", tags: ["família", "reunião", "barulho com amor"], destaque: true,
    pexelsQuery: "full house family gathering noisy",
  },
  {
    titulo: "Laços Que Não Quebram",
    texto: "Pode passar anos sem se ver. Mas quando a família se encontra, é como se o tempo não tivesse passado.",
    categoria: "familia", tags: ["família", "laços", "reencontro"], destaque: false,
    pexelsQuery: "family reunion bond unbreakable",
  },
  {
    titulo: "Colo de Mãe",
    texto: "Não importa a idade. No colo da mãe, você sempre vai ser o filho que precisa de carinho.",
    categoria: "familia", tags: ["família", "mãe", "colo"], destaque: false,
    pexelsQuery: "mother child embrace lap love",
  },
  {
    titulo: "Exemplo de Pai",
    texto: "Pai presente vale mais que mil presentes. Obrigado por estar aqui.",
    categoria: "familia", tags: ["família", "pai", "presença"], destaque: false,
    pexelsQuery: "present father family gift presence",
  },
  {
    titulo: "Família Escolhida",
    texto: "Tem família que a gente não escolhe mas ama. E tem família que a gente escolhe e também ama. As duas são reais.",
    categoria: "familia", tags: ["família", "escolha", "amizade"], destaque: false,
    pexelsQuery: "chosen family friends love together",
  },

  // ── MOTIVAÇÃO (20) ────────────────────────────────────────────────────────
  {
    titulo: "Você Não Para Aqui",
    texto: "O que você está sentindo agora é temporário. O que você está construindo é permanente. Não para aqui.",
    categoria: "motivacao", tags: ["motivação", "força", "perseverança"], destaque: true,
    pexelsQuery: "keep going motivation strength",
  },
  {
    titulo: "A Queda Faz Parte",
    texto: "Cair não te define. Levantar te define. E você já se levantou antes — vai se levantar de novo.",
    categoria: "motivacao", tags: ["motivação", "resiliência", "recomeço"], destaque: false,
    pexelsQuery: "rise fall resilience strength",
  },
  {
    titulo: "Seu Tempo Vai Chegar",
    texto: "Não compare sua jornada com a de ninguém. O seu tempo vai chegar. Na hora certa.",
    categoria: "motivacao", tags: ["motivação", "tempo", "jornada"], destaque: false,
    pexelsQuery: "your time journey own path",
  },
  {
    titulo: "Feito de Vitórias",
    texto: "Você é feito de cada obstáculo que superou, cada noite que aguentou e cada manhã que decidiu tentar de novo.",
    categoria: "motivacao", tags: ["motivação", "vitória", "superação"], destaque: true,
    pexelsQuery: "made of victories overcome success",
  },
  {
    titulo: "Um Passo de Cada Vez",
    texto: "Não precisa ver o caminho inteiro. Só precisa do próximo passo. Só um.",
    categoria: "motivacao", tags: ["motivação", "foco", "começo"], destaque: false,
    pexelsQuery: "one step at a time path forward",
  },
  {
    titulo: "A Dor Vai Passar",
    texto: "A dor que você sente hoje é o preço da força que você vai ter amanhã. Aguenta.",
    categoria: "motivacao", tags: ["motivação", "dor", "crescimento"], destaque: false,
    pexelsQuery: "pain strength tomorrow grow",
  },
  {
    titulo: "Você É Capaz",
    texto: "Antes de qualquer um acreditar em você, você precisa acreditar em você. Começa por aí.",
    categoria: "motivacao", tags: ["motivação", "autoconfiança", "crença"], destaque: false,
    pexelsQuery: "believe yourself capable confidence",
  },
  {
    titulo: "Medo É Normal",
    texto: "Sentir medo é normal. Deixar o medo decidir por você não é. Vai mesmo assim.",
    categoria: "motivacao", tags: ["motivação", "medo", "coragem"], destaque: true,
    pexelsQuery: "face fear courage brave",
  },
  {
    titulo: "Consistência Vence",
    texto: "Talento sem consistência vai embora. Consistência sem talento chega lá. Continua aparecendo todo dia.",
    categoria: "motivacao", tags: ["motivação", "consistência", "disciplina"], destaque: false,
    pexelsQuery: "consistency discipline daily habit",
  },
  {
    titulo: "Sua Melhor Versão",
    texto: "Você não precisa ser o melhor do mundo. Só precisa ser melhor do que você era ontem.",
    categoria: "motivacao", tags: ["motivação", "evolução", "progresso"], destaque: false,
    pexelsQuery: "better version self improve grow",
  },
  {
    titulo: "Sonho Que Custa",
    texto: "Se o seu sonho não te assusta um pouco, talvez ele seja pequeno demais pra você.",
    categoria: "motivacao", tags: ["motivação", "sonho", "ambição"], destaque: false,
    pexelsQuery: "dream big goal ambitious",
  },
  {
    titulo: "Não Desiste Fácil",
    texto: "O sucesso foi na porta de muita gente. A maioria não abriu porque achava que era tarde.",
    categoria: "motivacao", tags: ["motivação", "sucesso", "persistência"], destaque: true,
    pexelsQuery: "success door opportunity knock",
  },
  {
    titulo: "Você Já Chegou Longe",
    texto: "Para um segundo e olha pra trás. Veja quanto você já andou. Você merece esse reconhecimento.",
    categoria: "motivacao", tags: ["motivação", "reconhecimento", "progresso"], destaque: false,
    pexelsQuery: "how far come progress look back",
  },
  {
    titulo: "Dificuldade É Escola",
    texto: "Nenhuma dificuldade é inútil. Cada uma te ensina algo que só ela poderia ensinar.",
    categoria: "motivacao", tags: ["motivação", "dificuldade", "aprendizado"], destaque: false,
    pexelsQuery: "difficulty lesson learn school life",
  },
  {
    titulo: "Hora de Agir",
    texto: "Pensar é importante. Mas em algum momento você tem que parar de planejar e simplesmente agir.",
    categoria: "motivacao", tags: ["motivação", "ação", "decisão"], destaque: false,
    pexelsQuery: "action decision move forward",
  },
  {
    titulo: "Você Foi Feito pra Isso",
    texto: "A vida não te colocou nessa situação por acaso. Você tem o que é preciso pra sair dela.",
    categoria: "motivacao", tags: ["motivação", "propósito", "força"], destaque: false,
    pexelsQuery: "made for this purpose strength",
  },
  {
    titulo: "Vitória Que Vem",
    texto: "A sua vitória não está atrasada. Está sendo construída. Cada dia difícil é um tijolo no alicerce.",
    categoria: "motivacao", tags: ["motivação", "vitória", "construção"], destaque: true,
    pexelsQuery: "victory coming building success",
  },
  {
    titulo: "Foco No Que Importa",
    texto: "Pare de desperdiçar energia com quem não acredita em você. Foco em quem apoia e no seu caminho.",
    categoria: "motivacao", tags: ["motivação", "foco", "energia"], destaque: false,
    pexelsQuery: "focus energy priority what matters",
  },
  {
    titulo: "Recomeçar É Corajoso",
    texto: "Recomeçar do zero não é fracasso. É coragem de admitir que você merece algo melhor.",
    categoria: "motivacao", tags: ["motivação", "recomeço", "coragem"], destaque: false,
    pexelsQuery: "restart courage new beginning",
  },
  {
    titulo: "Você Está No Caminho",
    texto: "Não se sinta perdido. Cada desvio faz parte da rota. Você está exatamente onde precisa estar.",
    categoria: "motivacao", tags: ["motivação", "caminho", "confiança"], destaque: false,
    pexelsQuery: "right path journey trust route",
  },

  // ── AMIZADE (20) ──────────────────────────────────────────────────────────
  {
    titulo: "Amigo de Verdade",
    texto: "Amigo de verdade não some quando você está bem. Aparece quando você está mal. E fica.",
    categoria: "amizade", tags: ["amizade", "lealdade", "presença"], destaque: true,
    pexelsQuery: "true friend loyal together support",
  },
  {
    titulo: "Risada Que Cura",
    texto: "Tem gente que te faz rir do jeito que cura. Cuida dessas pessoas. São raras.",
    categoria: "amizade", tags: ["amizade", "risada", "alegria"], destaque: false,
    pexelsQuery: "friends laughing joy together",
  },
  {
    titulo: "Saudade de Amigo",
    texto: "Tem uma saudade boa que dói. É a saudade de amigo. A que faz a gente sorrir enquanto sente falta.",
    categoria: "amizade", tags: ["amizade", "saudade", "carinho"], destaque: false,
    pexelsQuery: "missing friend nostalgia smile",
  },
  {
    titulo: "Amizade Que Dura",
    texto: "Pode passar anos sem se ver. Uma amizade verdadeira começa de onde parou.",
    categoria: "amizade", tags: ["amizade", "duradoura", "distância"], destaque: true,
    pexelsQuery: "lasting friendship long distance time",
  },
  {
    titulo: "Obrigado Por Estar Aqui",
    texto: "Obrigado por ser aquele/a que está quando os outros foram embora. Você significa muito pra mim.",
    categoria: "amizade", tags: ["amizade", "gratidão", "presença"], destaque: false,
    pexelsQuery: "friend gratitude be there support",
  },
  {
    titulo: "Você Me Conhece",
    texto: "A melhor coisa de um amigo de verdade é que ele te conhece inteiro e te ama do mesmo jeito.",
    categoria: "amizade", tags: ["amizade", "aceitação", "conhecimento"], destaque: false,
    pexelsQuery: "know me friend accept love",
  },
  {
    titulo: "Amigo É Família",
    texto: "Nem sempre a família é de sangue. Às vezes o amigo que Deus colocou na sua vida é mais família do que qualquer outro.",
    categoria: "amizade", tags: ["amizade", "família", "escolha"], destaque: false,
    pexelsQuery: "friend family chosen bond",
  },
  {
    titulo: "Cada Aventura Juntos",
    texto: "A vida fica melhor quando você tem alguém pra dividir cada aventura. Você é essa pessoa pra mim.",
    categoria: "amizade", tags: ["amizade", "aventura", "parceria"], destaque: false,
    pexelsQuery: "adventure friends together journey",
  },
  {
    titulo: "Sem Julgamento",
    texto: "Que bom ter um amigo com quem você não precisa se explicar. Que te aceita sem precisar de contexto.",
    categoria: "amizade", tags: ["amizade", "aceitação", "sem julgamento"], destaque: true,
    pexelsQuery: "no judgment friend accept trust",
  },
  {
    titulo: "Parceiro de Vida",
    texto: "Amizade boa não é sobre quantidade de tempo juntos. É sobre qualidade do que vivem quando estão.",
    categoria: "amizade", tags: ["amizade", "qualidade", "presença"], destaque: false,
    pexelsQuery: "quality friendship life partner",
  },
  {
    titulo: "Liga Só Pra Ver",
    texto: "Aquele amigo que liga sem motivo, só pra saber como você tá — guarda esse com a sua vida.",
    categoria: "amizade", tags: ["amizade", "cuidado", "atenção"], destaque: false,
    pexelsQuery: "call friend check on care phone",
  },
  {
    titulo: "Amigo do Peito",
    texto: "Todo mundo precisa de um amigo do peito. Aquele que guarda os segredos e divide os sonhos.",
    categoria: "amizade", tags: ["amizade", "segredo", "confiança"], destaque: false,
    pexelsQuery: "best friend secret trust close",
  },
  {
    titulo: "Na Hora Difícil",
    texto: "Você descobre quem são seus amigos na hora difícil. Os que ficam valem mais do que ouro.",
    categoria: "amizade", tags: ["amizade", "dificuldade", "lealdade"], destaque: true,
    pexelsQuery: "friend hard time support difficult",
  },
  {
    titulo: "Feliz Por Você",
    texto: "Amigo de verdade fica feliz com a sua vitória como se fosse dele. É esse tipo que importa.",
    categoria: "amizade", tags: ["amizade", "generosidade", "alegria"], destaque: false,
    pexelsQuery: "friend happy your victory celebrate",
  },
  {
    titulo: "Cumplicidade",
    texto: "Existe uma linguagem entre amigos de verdade que não precisa de palavras. Um olhar já basta.",
    categoria: "amizade", tags: ["amizade", "cumplicidade", "conexão"], destaque: false,
    pexelsQuery: "friends eye contact complicit bond",
  },
  {
    titulo: "Amizade Antiga",
    texto: "Amizade antiga é como vinho bom: só melhora com o tempo.",
    categoria: "amizade", tags: ["amizade", "tempo", "valor"], destaque: false,
    pexelsQuery: "old friendship wine better time",
  },
  {
    titulo: "Quero Seu Bem",
    texto: "Um verdadeiro amigo é aquele que quer seu bem mesmo quando isso não inclui ele.",
    categoria: "amizade", tags: ["amizade", "bem querer", "generosidade"], destaque: false,
    pexelsQuery: "friend want best for you selfless",
  },
  {
    titulo: "Rir Até Chorar",
    texto: "Que você sempre tenha um amigo com quem rir até chorar. Esse riso é remédio pra alma.",
    categoria: "amizade", tags: ["amizade", "risada", "cura"], destaque: true,
    pexelsQuery: "laugh until cry friends together",
  },
  {
    titulo: "Nossa Bagunça",
    texto: "Nossa amizade é uma bagunça linda. E eu não trocaria por nada do mundo.",
    categoria: "amizade", tags: ["amizade", "bagunça", "amor"], destaque: false,
    pexelsQuery: "messy beautiful friendship fun",
  },
  {
    titulo: "Gratidão Por Você",
    texto: "Sou grato/a por ter você na minha vida. Você faz tudo mais fácil, mais leve e mais bonito.",
    categoria: "amizade", tags: ["amizade", "gratidão", "leveza"], destaque: false,
    pexelsQuery: "grateful friend lighter life beautiful",
  },

  // ── ANIVERSÁRIO (20) ──────────────────────────────────────────────────────
  {
    titulo: "Parabéns, Você Chegou!",
    texto: "Parabéns! Mais um ano de vida vivida, aprendida e conquistada. Que venham muitos mais!",
    categoria: "aniversario", tags: ["aniversário", "parabéns", "vida"], destaque: true,
    pexelsQuery: "birthday celebration balloons confetti",
  },
  {
    titulo: "Feliz Aniversário Com Amor",
    texto: "Feliz aniversário! Que esse dia seja o reflexo de tudo que você é: incrível, único/a e especial.",
    categoria: "aniversario", tags: ["aniversário", "especial", "amor"], destaque: false,
    pexelsQuery: "happy birthday love special unique",
  },
  {
    titulo: "Um Ano Mais Forte",
    texto: "A cada ano que passa, você se torna mais você. Mais forte, mais sábio/a, mais completo/a. Parabéns!",
    categoria: "aniversario", tags: ["aniversário", "crescimento", "força"], destaque: false,
    pexelsQuery: "birthday stronger wiser grow year",
  },
  {
    titulo: "Que Venha Tudo de Bom",
    texto: "No seu aniversário, que tudo que você plantou com esforço venha em colheita abundante. Parabéns!",
    categoria: "aniversario", tags: ["aniversário", "bênção", "colheita"], destaque: true,
    pexelsQuery: "birthday harvest abundance blessings",
  },
  {
    titulo: "Você Merece Celebrar",
    texto: "Você merece cada parabéns, cada abraço e cada pedaço de bolo hoje. Feliz aniversário!",
    categoria: "aniversario", tags: ["aniversário", "celebração", "merecimento"], destaque: false,
    pexelsQuery: "deserve celebrate birthday cake joy",
  },
  {
    titulo: "Mais Um Capítulo",
    texto: "Mais um capítulo dessa história linda que é a sua vida. Feliz aniversário! Que os próximos sejam ainda mais bonitos.",
    categoria: "aniversario", tags: ["aniversário", "história", "vida"], destaque: false,
    pexelsQuery: "birthday chapter life story book",
  },
  {
    titulo: "Dia Seu",
    texto: "Hoje é o seu dia. Receba amor, atenção e tudo de bom que você distribuiu por aí. Parabéns!",
    categoria: "aniversario", tags: ["aniversário", "dia especial", "amor"], destaque: false,
    pexelsQuery: "your day birthday special receive love",
  },
  {
    titulo: "Amigo de Aniversário",
    texto: "Feliz aniversário, meu amigo/a! Que essa data te lembre o quanto você importa pra quem tem a sorte de te ter por perto.",
    categoria: "aniversario", tags: ["aniversário", "amizade", "importância"], destaque: false,
    pexelsQuery: "birthday friend celebration joy",
  },
  {
    titulo: "Seus Sonhos Realizados",
    texto: "No seu aniversário, que cada sonho que você ainda não contou pra ninguém comece a se realizar. Parabéns!",
    categoria: "aniversario", tags: ["aniversário", "sonhos", "realização"], destaque: true,
    pexelsQuery: "birthday dreams come true wish",
  },
  {
    titulo: "Saúde e Alegria",
    texto: "Feliz aniversário! Que você tenha saúde pra viver, alegria pra sentir e amor pra compartilhar.",
    categoria: "aniversario", tags: ["aniversário", "saúde", "alegria"], destaque: false,
    pexelsQuery: "birthday health happiness joy life",
  },
  {
    titulo: "Filho Que Me Orgulha",
    texto: "Você faz cada ano da minha vida mais especial. Feliz aniversário, filho/a! Te amo infinito.",
    categoria: "aniversario", tags: ["aniversário", "filho", "orgulho"], destaque: false,
    pexelsQuery: "parent child birthday proud love",
  },
  {
    titulo: "Parabéns Meu Amor",
    texto: "Feliz aniversário, amor! Que esse ano seja tão especial quanto você é pra mim. Te amo.",
    categoria: "aniversario", tags: ["aniversário", "amor", "casal"], destaque: true,
    pexelsQuery: "birthday love couple romantic celebrate",
  },
  {
    titulo: "Muitas Conquistas",
    texto: "Parabéns! Que esse novo ano da sua vida traga muitas conquistas, poucas perdas e muito amor.",
    categoria: "aniversario", tags: ["aniversário", "conquistas", "novo ano"], destaque: false,
    pexelsQuery: "birthday achievements new year ahead",
  },
  {
    titulo: "Que Deus Abençoe",
    texto: "No seu dia, que Deus derrame bênçãos sobre você, sua família e todos os seus planos. Feliz aniversário!",
    categoria: "aniversario", tags: ["aniversário", "bênção", "fé"], destaque: false,
    pexelsQuery: "birthday blessing God faith celebrate",
  },
  {
    titulo: "Aniversário da Mãe",
    texto: "Feliz aniversário, mãe! Você é o maior presente que a vida me deu. Te amo mais do que posso expressar.",
    categoria: "aniversario", tags: ["aniversário", "mãe", "amor"], destaque: false,
    pexelsQuery: "mother birthday gift love family",
  },
  {
    titulo: "Parabéns, Pai!",
    texto: "Feliz aniversário, pai! Por tudo que você fez, faz e ainda vai fazer. Você é meu exemplo.",
    categoria: "aniversario", tags: ["aniversário", "pai", "exemplo"], destaque: false,
    pexelsQuery: "father birthday example hero celebrate",
  },
  {
    titulo: "Viva Você!",
    texto: "Hoje é dia de celebrar a vida, e você é o maior motivo de celebração. Viva você! Feliz aniversário!",
    categoria: "aniversario", tags: ["aniversário", "celebração", "vida"], destaque: false,
    pexelsQuery: "celebrate life birthday party cheer",
  },
  {
    titulo: "Surpresas Boas Vêm",
    texto: "Feliz aniversário! Que esse ano te surpreenda com coisas que você nem sonhou em pedir.",
    categoria: "aniversario", tags: ["aniversário", "surpresa", "esperança"], destaque: true,
    pexelsQuery: "surprise birthday unexpected good things",
  },
  {
    titulo: "Irmão de Aniversário",
    texto: "Parabéns, irmão/irmã! Crescer com você foi e continua sendo uma das melhores coisas da minha vida.",
    categoria: "aniversario", tags: ["aniversário", "irmão", "memória"], destaque: false,
    pexelsQuery: "sibling birthday grow together celebrate",
  },
  {
    titulo: "Luz Que Você É",
    texto: "Feliz aniversário! Que a luz que você espalha por onde passa volte pra você multiplicada.",
    categoria: "aniversario", tags: ["aniversário", "luz", "retorno"], destaque: false,
    pexelsQuery: "light birthday spread return multiply",
  },

  // ── REFLEXÃO (20) ─────────────────────────────────────────────────────────
  {
    titulo: "O Que Você Planta",
    texto: "Você colhe o que planta. Então plante gentileza, paciência e esforço. A colheita vem.",
    categoria: "reflexao", tags: ["reflexão", "colheita", "escolhas"], destaque: true,
    pexelsQuery: "plant harvest choices life",
  },
  {
    titulo: "Tempo Que Não Volta",
    texto: "O tempo é a única coisa que não volta. Use-o com quem vale, em coisas que importam.",
    categoria: "reflexao", tags: ["reflexão", "tempo", "prioridade"], destaque: false,
    pexelsQuery: "time clock precious value",
  },
  {
    titulo: "Aceitar Sem Prender",
    texto: "Aceitar não é concordar. É soltar o peso de brigar com o que não pode mudar.",
    categoria: "reflexao", tags: ["reflexão", "aceitação", "paz"], destaque: false,
    pexelsQuery: "acceptance let go peace weight",
  },
  {
    titulo: "Silêncio Que Fala",
    texto: "Às vezes o silêncio diz mais do que qualquer palavra. Aprenda a ouvi-lo.",
    categoria: "reflexao", tags: ["reflexão", "silêncio", "sabedoria"], destaque: false,
    pexelsQuery: "silence speak wisdom quiet",
  },
  {
    titulo: "Humildade É Força",
    texto: "Humildade não é fraqueza. É a sabedoria de saber que você ainda tem muito a aprender.",
    categoria: "reflexao", tags: ["reflexão", "humildade", "sabedoria"], destaque: true,
    pexelsQuery: "humility strength wisdom learn",
  },
  {
    titulo: "Cada Fase Tem Lição",
    texto: "Nenhuma fase da vida é inútil. Cada uma tem uma lição embutida. Presta atenção.",
    categoria: "reflexao", tags: ["reflexão", "fase", "aprendizado"], destaque: false,
    pexelsQuery: "life phase lesson learn growth",
  },
  {
    titulo: "Comparação Rouba",
    texto: "Comparação rouba a alegria. Olhe menos para o lado e mais para o seu próprio caminho.",
    categoria: "reflexao", tags: ["reflexão", "comparação", "foco"], destaque: false,
    pexelsQuery: "compare joy steal own path",
  },
  {
    titulo: "Perdoar É Libertar",
    texto: "Perdoar não é dar razão a quem errou. É se libertar do peso que o ressentimento coloca em você.",
    categoria: "reflexao", tags: ["reflexão", "perdão", "liberdade"], destaque: true,
    pexelsQuery: "forgive free liberation peace",
  },
  {
    titulo: "Menos É Mais",
    texto: "Em algum momento da vida você aprende: menos relações mas mais profundas vale muito mais.",
    categoria: "reflexao", tags: ["reflexão", "qualidade", "relacionamentos"], destaque: false,
    pexelsQuery: "less more quality deep relationships",
  },
  {
    titulo: "Você É Suficiente",
    texto: "Você não precisa ser mais, ter mais ou fazer mais pra ser suficiente. Você já é.",
    categoria: "reflexao", tags: ["reflexão", "autoestima", "suficiência"], destaque: false,
    pexelsQuery: "enough sufficient self worth value",
  },
  {
    titulo: "Mude O Que Pode",
    texto: "Não perca energia com o que você não pode mudar. Direcione tudo pro que você pode.",
    categoria: "reflexao", tags: ["reflexão", "controle", "foco"], destaque: false,
    pexelsQuery: "change what you can control focus",
  },
  {
    titulo: "Palavras Têm Peso",
    texto: "Palavras constroem ou destroem. Escolha as suas com cuidado — elas ficam depois que a voz vai embora.",
    categoria: "reflexao", tags: ["reflexão", "palavras", "cuidado"], destaque: true,
    pexelsQuery: "words weight careful power",
  },
  {
    titulo: "Pequenos Gestos",
    texto: "As maiores memórias são feitas de pequenos gestos. Um abraço na hora certa vale mais que mil presentes.",
    categoria: "reflexao", tags: ["reflexão", "gestos", "memória"], destaque: false,
    pexelsQuery: "small gestures big memories moments",
  },
  {
    titulo: "Nada É Eterno",
    texto: "Nada é eterno — nem a dor, nem a alegria. Aproveite o bom enquanto dura e aguenta que o ruim vai passar.",
    categoria: "reflexao", tags: ["reflexão", "impermanência", "sabedoria"], destaque: false,
    pexelsQuery: "nothing eternal impermanence life moment",
  },
  {
    titulo: "Seu Interior Primeiro",
    texto: "Cuide do seu interior primeiro. Quando a paz vem de dentro, nada de fora consegue te roubar.",
    categoria: "reflexao", tags: ["reflexão", "interior", "paz"], destaque: false,
    pexelsQuery: "inner peace soul interior first",
  },
  {
    titulo: "Gratidão Transforma",
    texto: "Uma mente grata é uma mente em paz. Quando você para para agradecer, muda a perspectiva de tudo.",
    categoria: "reflexao", tags: ["reflexão", "gratidão", "perspectiva"], destaque: true,
    pexelsQuery: "gratitude transform perspective thankful",
  },
  {
    titulo: "Errar É Humano",
    texto: "Errar faz de você humano. Aprender com o erro faz de você sábio. Não se puna demais.",
    categoria: "reflexao", tags: ["reflexão", "erro", "aprendizado"], destaque: false,
    pexelsQuery: "mistake human learn wise forgive self",
  },
  {
    titulo: "Quem Você É Em Privado",
    texto: "O caráter se revela não em público, mas em quem você é quando ninguém está olhando.",
    categoria: "reflexao", tags: ["reflexão", "caráter", "integridade"], destaque: false,
    pexelsQuery: "character private integrity who you are",
  },
  {
    titulo: "Amor Próprio É Base",
    texto: "Você não pode dar o que não tem. Cuide de você primeiro. O amor próprio é a base de tudo.",
    categoria: "reflexao", tags: ["reflexão", "amor próprio", "base"], destaque: false,
    pexelsQuery: "self love foundation base care",
  },
  {
    titulo: "O Agora É Tudo",
    texto: "O passado já foi. O futuro ainda não chegou. O presente é o único lugar onde a vida acontece.",
    categoria: "reflexao", tags: ["reflexão", "presente", "mindfulness"], destaque: true,
    pexelsQuery: "present moment now mindful live",
  },

  // ── DATAS COMEMORATIVAS (20) ──────────────────────────────────────────────
  {
    titulo: "Natal de Amor",
    texto: "Natal não é sobre presentes debaixo da árvore. É sobre amor, paz e as pessoas que você escolhe ter perto.",
    categoria: "datas-comemorativas", tags: ["natal", "amor", "família"], destaque: true,
    pexelsQuery: "Christmas love family warmth",
  },
  {
    titulo: "Feliz Ano Novo",
    texto: "Que o ano que chega traga novas forças, novos começos e muito do que você ainda está esperando.",
    categoria: "datas-comemorativas", tags: ["ano novo", "esperança", "recomeço"], destaque: true,
    pexelsQuery: "new year fireworks celebrate hope",
  },
  {
    titulo: "Páscoa e Renovação",
    texto: "A Páscoa nos lembra que todo fim tem um recomeço. Que essa data traga renovação pra sua vida.",
    categoria: "datas-comemorativas", tags: ["páscoa", "renovação", "esperança"], destaque: false,
    pexelsQuery: "Easter renewal hope flowers spring",
  },
  {
    titulo: "Dia das Mães",
    texto: "Nenhuma data é grande o suficiente para homenagear tudo que uma mãe representa. Mas hoje tentamos.",
    categoria: "datas-comemorativas", tags: ["dia das mães", "mãe", "amor"], destaque: true,
    pexelsQuery: "mothers day flowers love",
  },
  {
    titulo: "Dia dos Pais",
    texto: "Pai presente é o maior presente. Feliz Dia dos Pais pra quem constrói, protege e ama sem parar.",
    categoria: "datas-comemorativas", tags: ["dia dos pais", "pai", "amor"], destaque: true,
    pexelsQuery: "fathers day dad love family",
  },
  {
    titulo: "Dia dos Namorados",
    texto: "Amor não precisa de data. Mas hoje é um lembrete especial pra dizer: você é a melhor coisa que aconteceu pra mim.",
    categoria: "datas-comemorativas", tags: ["dia dos namorados", "amor", "casal"], destaque: true,
    pexelsQuery: "valentines day couple love romantic",
  },
  {
    titulo: "Janeiro Branco",
    texto: "Janeiro Branco é convite à reflexão. Cuide da sua saúde mental com o mesmo carinho que cuida do corpo.",
    categoria: "datas-comemorativas", tags: ["janeiro branco", "saúde mental", "reflexão"], destaque: false,
    pexelsQuery: "mental health white January peace mind",
  },
  {
    titulo: "Fevereiro Roxo",
    texto: "Fevereiro Roxo nos lembra: falar sobre lúpus e fibromialgia é cuidar de quem sofre em silêncio.",
    categoria: "datas-comemorativas", tags: ["fevereiro roxo", "saúde", "conscientização"], destaque: false,
    pexelsQuery: "purple February awareness health",
  },
  {
    titulo: "Março Lilás",
    texto: "Março Lilás: conscientização sobre a endometriose. Ouvir, crer e apoiar quem sente essa dor invisível.",
    categoria: "datas-comemorativas", tags: ["março lilás", "endometriose", "saúde feminina"], destaque: false,
    pexelsQuery: "lilac March woman health awareness",
  },
  {
    titulo: "Abril Azul",
    texto: "Abril Azul é sobre entender, incluir e celebrar as pessoas com autismo. Aceitar é o primeiro passo.",
    categoria: "datas-comemorativas", tags: ["abril azul", "autismo", "inclusão"], destaque: false,
    pexelsQuery: "blue April autism awareness inclusion",
  },
  {
    titulo: "Maio Amarelo",
    texto: "Maio Amarelo: o sinal que pede atenção. Trânsito seguro começa com respeito pela vida.",
    categoria: "datas-comemorativas", tags: ["maio amarelo", "trânsito", "vida"], destaque: false,
    pexelsQuery: "yellow May traffic safe life",
  },
  {
    titulo: "Junho Vermelho",
    texto: "Junho Vermelho: doe sangue, doe vida. Um simples gesto seu pode salvar até quatro pessoas.",
    categoria: "datas-comemorativas", tags: ["junho vermelho", "doação de sangue", "vida"], destaque: false,
    pexelsQuery: "red June blood donation save life",
  },
  {
    titulo: "Julho Amarelo",
    texto: "Julho Amarelo: prevenção às hepatites virais. Cuide-se e informe quem você ama.",
    categoria: "datas-comemorativas", tags: ["julho amarelo", "hepatite", "saúde"], destaque: false,
    pexelsQuery: "yellow July hepatitis health prevention",
  },
  {
    titulo: "Agosto Dourado",
    texto: "Agosto Dourado celebra o aleitamento materno. O leite materno é amor líquido e proteção desde o início da vida.",
    categoria: "datas-comemorativas", tags: ["agosto dourado", "amamentação", "vida"], destaque: false,
    pexelsQuery: "golden August breastfeeding mother baby",
  },
  {
    titulo: "Setembro Amarelo",
    texto: "Setembro Amarelo: falar sobre suicídio salva vidas. Pergunte como a pessoa está. De verdade.",
    categoria: "datas-comemorativas", tags: ["setembro amarelo", "saúde mental", "vida"], destaque: true,
    pexelsQuery: "yellow September life mental health care",
  },
  {
    titulo: "Outubro Rosa",
    texto: "Outubro Rosa é sobre prevenção, mas também sobre força. Toda mulher que luta merece ser celebrada.",
    categoria: "datas-comemorativas", tags: ["outubro rosa", "câncer de mama", "força feminina"], destaque: true,
    pexelsQuery: "pink October breast cancer strength woman",
  },
  {
    titulo: "Novembro Azul",
    texto: "Novembro Azul: saúde do homem também importa. Cuidar-se não é fraqueza, é inteligência.",
    categoria: "datas-comemorativas", tags: ["novembro azul", "saúde masculina", "prevenção"], destaque: false,
    pexelsQuery: "blue November mens health awareness",
  },
  {
    titulo: "Dezembro Laranja",
    texto: "Dezembro Laranja: combate ao acidente vascular cerebral. Reconheça os sinais e aja rápido.",
    categoria: "datas-comemorativas", tags: ["dezembro laranja", "AVC", "saúde"], destaque: false,
    pexelsQuery: "orange December stroke health awareness",
  },
  {
    titulo: "Dia da Amizade",
    texto: "Amizade não precisa de data comemorativa pra ser celebrada. Mas hoje serve como lembrete pra falar com quem você ama.",
    categoria: "datas-comemorativas", tags: ["dia da amizade", "amizade", "celebração"], destaque: false,
    pexelsQuery: "friendship day celebrate friends together",
  },
  {
    titulo: "Finados Com Amor",
    texto: "Finados não é sobre a morte. É sobre a saudade de quem viveu, amou e deixou marca.",
    categoria: "datas-comemorativas", tags: ["finados", "saudade", "memória"], destaque: false,
    pexelsQuery: "all souls day memory flowers love",
  },
];
